const PRODUCTS = [
  {index:"01",name:"Bio-Diesel",description:"A renewable, biodegradable fuel manufactured from vegetable oils and animal fats. Reduces particulate emissions while delivering performance comparable to petroleum diesel.",applications:["Commercial logistics fleets","Power generation sets","Agricultural equipment","Industrial diesel engines"]},
  {index:"02",name:"LDO",description:"Light Diesel Oil — a heavier distillate used where furnace oil is too viscous and high-speed diesel is uneconomical. Stable combustion and reliable supply.",applications:["Industrial furnaces","Lift irrigation pumps","DG sets","Tractor engines"]},
  {index:"03",name:"Bitumen",description:"Viscoelastic binder available in VG-10, VG-30 and VG-40 grades. Engineered for road surfacing, industrial flooring and waterproof membranes.",applications:["Highway construction","Roofing membranes","Industrial flooring","Hydraulic structures"]},
  {index:"04",name:"Furnace Oil",description:"Heavy residual fuel oil tuned for high-output industrial heating. Cost-efficient thermal energy for continuous-duty operations.",applications:["Steel rolling mills","Brick kilns","Industrial boilers","Cement plants"]},
  {index:"05",name:"LSHS",description:"Low Sulphur Heavy Stock — a refined residual fuel that meets stricter emission thresholds without compromising calorific value.",applications:["Glass furnaces","Captive power plants","Process heating","Marine bunkering"]},
  {index:"06",name:"Industrial Fuel",description:"Refined industrial fuel oil produced in two variants: White IFO for cleaner-burning applications and Black IFO for high-thermal-load processes.",applications:["Heavy manufacturing","Forging units","Textile processing","Chemical plants"]},
  {index:"07",name:"Bakery Oil",description:"A clean-burning, low-residue fuel oil specifically blended for bakery ovens and food-grade thermal processes. Consistent flame profile and minimal soot.",applications:["Commercial bakeries","Biscuit ovens","Confectionery units","Food-grade thermal lines"]}
];
